####Import libraries

In [12]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

####Importing the dataset

In [13]:
dataset = pd.read_csv('TravelInfo.csv')
dataset.head()

Age  Income  TravelAbroad
0   22   25000             0
1   38   26000             0
2   29   49000             0
3   30   63000             0
4   22   82000             0

####Separate features (x) and the target variables (y)

In [14]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

####Split dataset into Training and Test set

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [16]:
X_train

array([[    47,  45000],
       [    35, 126000],
       [    41,  56000],
       [    35, 141000],
       [    55,  27000],
       [    56, 110000],
       [    42,  48000],
       [    41,  67000],
       [    39,  56000],
       [    39,  69000],
       [    38,  31000],
       [    38,  56000],
       [    45,  79000],
       [    50,  55000],
       [    62,  35000],
       [    52,  71000],
       [    48, 137000],
       [    34,  95000],
       [    49,  88000],
       [    50,  57000],
       [    29,  21000],
       [    63, 108000],
       [    41, 118000],
       [    43, 113000],
       [    45,  59000],
       [    38,  65000],
       [    51,  47000],
       [    51, 140000],
       [    41, 119000],
       [    32, 154000],
       [    29,  21000],
       [    63,  48000],
       [    27,  25000],
       [    45, 155000],
       [    49, 102000],
       [    31,  65000],
       [    42, 102000],
       [    31,  95000],
       [    44,  78000],
       [    48,  32000],


####Scale features

In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [18]:
X_train

array([[ 0.58164944, -0.88670699],
       [-0.60673761,  1.46173768],
       [-0.01254409, -0.5677824 ],
       [-0.60673761,  1.89663484],
       [ 1.37390747, -1.40858358],
       [ 1.47293972,  0.99784738],
       [ 0.08648817, -0.79972756],
       [-0.01254409, -0.24885782],
       [-0.21060859, -0.5677824 ],
       [-0.21060859, -0.19087153],
       [-0.30964085, -1.29261101],
       [-0.30964085, -0.5677824 ],
       [ 0.38358493,  0.09905991],
       [ 0.8787462 , -0.59677555],
       [ 2.06713324, -1.17663843],
       [ 1.07681071, -0.13288524],
       [ 0.68068169,  1.78066227],
       [-0.70576986,  0.56295021],
       [ 0.77971394,  0.35999821],
       [ 0.8787462 , -0.53878926],
       [-1.20093113, -1.58254245],
       [ 2.1661655 ,  0.93986109],
       [-0.01254409,  1.22979253],
       [ 0.18552042,  1.08482681],
       [ 0.38358493, -0.48080297],
       [-0.30964085, -0.30684411],
       [ 0.97777845, -0.8287207 ],
       [ 0.97777845,  1.8676417 ],
       [-0.01254409,

####Training K-NN on Training set

In [19]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

#### Predict Test Results

In [20]:
y_pred = classifier.predict(X_test)

#### Confusion Matrix

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[64  4]
 [ 3 29]]


0.93

#### Predict new values



In [22]:
print(classifier.predict(sc.transform([[30,87000]])))

[0]
